import { poppins } from "@/ui/fonts";
import Navbar_two from "@/components/Navbar_two";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <div className="main-layout">
          <Navbar_two children={children}/>         
        </div>
      </body>
    </html>
  );
}
